### ISSUE TITLE
Synapse NullPotinerExeption on Join?

### ISSUE THREAD

**Issue by FilleDev** [PrismarineMC/MagmaBlock#4]
Sometimes I get this error when a player join:

[ALERT] Catch the exception in Synapse ticking: null
18:13:55 [ALERT] java.lang.NullPointerException
    at cn.nukkit.Player.handleDataPacket(Player.java:1787)
    at org.itxtech.synapseapi.SynapsePlayer.handleDataPacket(SynapsePlayer.java:444)
    at org.itxtech.synapseapi.SynapsePlayer.handleLoginPacket(SynapsePlayer.java:56)
    at org.itxtech.synapseapi.SynapseAPI.handleDataPacket(SynapseAPI.java:343)
    at org.itxtech.synapseapi.network.SynapseInterface.handlePacket(SynapseInterface.java:79)
    at org.itxtech.synapseapi.network.SynapseInterface.process(SynapseInterface.java:53)
    at org.itxtech.synapseapi.SynapseAPI.tick(SynapseAPI.java:247)
    at org.itxtech.synapseapi.SynapseAPI$Ticker.run(SynapseAPI.java:227)
    at java.lang.Thread.run(Thread.java:745)

**Comment by Encritary** [comment]
@File14 did you use 0.15.90?

**Comment by Encritary** [comment]
@File14 use latest MagmaBlock, i hava added npe fix on 0.15.90

**Comment by FilleDev** [comment]
Hopefully it's fixed. It happened when a 0.15.9 player tried to join I think.

**Comment by Encritary** [comment]
@File14 it is, I know
