### ISSUE TITLE
java.lang.IllegalArgumentException: Value 4.285714 exceeds the range!

### ISSUE THREAD

**Issue by FilleDev** [PrismarineMC/MagmaBlock#7]
[ALERT] java.lang.IllegalArgumentException: Value 4.285714 exceeds the range!
    at cn.nukkit.entity.Attribute.setValue(Attribute.java:144)
    at cn.nukkit.entity.Attribute.setValue(Attribute.java:138)
    at cn.nukkit.Player.sendExperience(Player.java:3620)
    at org.itxtech.synapseapi.SynapsePlayer.doFirstSpawn(SynapsePlayer.java:397)
    at cn.nukkit.Player.sendNextChunk(Player.java:674)
    at cn.nukkit.Player.checkNetwork(Player.java:1529)
    at cn.nukkit.Server.tick(Server.java:1046)
    at cn.nukkit.Server.tickProcessor(Server.java:834)
    at cn.nukkit.Server.start(Server.java:814)
    at cn.nukkit.Server.<init>(Server.java:487)
    at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by ghost** [comment]
@MrGenga

**Comment by Encritary** [comment]
@File14 player has invalid experience in .dat, try delete it

**Comment by File14** [comment]
I used the sendExperience wrong.
